.github/workflows/test.yml, runner-macros/src/entry.rs, runner/src/rpc/api.rs, runner/src/rpc/tool.rs
Addresses https://github.com/near/workspaces-rs/issues/13.
This adds a pipeline where clippy will be ran first, then if succeeds, moves onto running `cargo test`
=> feat: Github actions workflow

workspaces/src/rpc/api.rs, workspaces/src/runtime/local.rs, workspaces/src/runtime/mod.rs
Resolves https://github.com/near/workspaces-rs/issues/21
The idea is to hide all the verbose information provided by `FinalExceutionOutcomeView` and its constituents. For now we are only interested in the outcome of the call along with the total gas burnt by the execution.
=> Stop exposing `FinalExecutionOutcomeView` as the return type of many call-like functions

workspaces/Cargo.toml, workspaces/src/rpc/api.rs, workspaces/src/rpc/client.rs, workspaces/src/rpc/mod.rs, workspaces/src/rpc/tool.rs, workspaces/src/runtime/local.rs, workspaces/src/runtime/online.rs
Thought this was best to add next since CI builds are non-deterministic with sleeps and would fail sometimes. So all internal sleeps between each `call`/`view` function call are gone now. Also, won't likely have this for a while until near-api-rs is a thing in the middle, so might as well add it now and move it later.
`client.rs` handles most of the retry logic and also houses the logic for sending transactions
Also after this PR, completely addresses https://github.com/near/workspaces-rs/issues/7 by exposing mostly `anyhow::Result` for error handling, with the exception of one function left to be added by the spooning PR.
=> feat: exponential backoff for rpc calls

README.md
Some syntax wasn't valid, so updating so it's easier to follow
=> fix: Update Readme to updated and valid syntax

workspaces/Cargo.toml, workspaces/build.rs
Move installing the near-sandbox binary into `build.rs` as to not contend with multiple tests trying to install it at once.
Fixes: https://github.com/near/workspaces-rs/issues/44
=> bugfix: Fixup race condition when installing near-sandbox

examples/src/nft.rs, examples/src/ref_finance.rs, examples/src/spooning.rs, workspaces/src/network/account.rs, workspaces/src/network/mainnet.rs, workspaces/src/network/mod.rs, workspaces/src/network/sandbox.rs, workspaces/src/network/testnet.rs, workspaces/src/rpc/client.rs, workspaces/src/worker/impls.rs, workspaces/tests/patch_state.rs
There doesn't seem to me to be any requirement for these to be owned, given that they are just used to be serialized when sending a request. This is all very opinionated and I also have to think through the implications and future direction a lot more, but curious what you think @ChaoticTempest 
There were also some that could be changed with creating TLA (but this one seemed like owned might have a reason). Also, there are other parameters this could be done with, but trying to limit the scope.
=> refactor!: don't require owned AccountId for RPC abstractions

examples/Cargo.toml, examples/src/spooning.rs, workspaces/Cargo.toml, workspaces/src/network/server.rs, workspaces/tests/create_account.rs, workspaces/tests/deploy.rs, workspaces/tests/patch_state.rs
Fixes #26 
I chose `tracing` since this is what `nearcore` is using and due to its extensive features such as layered spans and subscription mechanisms that can be useful for monitoring further down the line. As per conversation under the issue, it does not necessarily tie us to `tokio` ecosystem either.
Unfortunately, the sandbox logs are being produced by a dynamically downloaded binary file, so they do not respect the logging configuration (`RUST_LOG`, `RUST_LOG_STYLE` and others). See #53. This means that for now users will see logs being printed in an inconsistent manner like this:
```
2022-01-12T01:05:05.814561Z  INFO workspaces: Starting up sandbox at localhost:15562
2022-01-12T01:05:05.814601Z  INFO workspaces: Starting up sandbox at localhost:15965
Jan 12 12:05:05.817  INFO …
```
=> feat: Switch prints to `tracing`

examples/src/nft.rs, examples/src/ref_finance.rs, examples/src/spooning.rs, examples/src/status_message.rs, workspaces/Cargo.toml, workspaces/src/network/account.rs, workspaces/src/network/mainnet.rs, workspaces/src/network/mod.rs, workspaces/src/network/sandbox.rs, workspaces/src/network/testnet.rs, workspaces/src/worker/impls.rs, workspaces/tests/deploy.rs, workspaces/tests/patch_state.rs
Refactored `account.deploy` and `worker.dev_deploy` to be consistent with each other
=> refactor: (dev_)deploy is now consistent across the board

examples/src/ref_finance.rs, workspaces/src/lib.rs, workspaces/src/network/mainnet.rs, workspaces/src/network/mod.rs, workspaces/src/rpc/patch.rs, workspaces/src/types.rs, workspaces/src/worker/mod.rs, workspaces/tests/patch_state.rs
This will fix the issue with https://github.com/near/workspaces-rs/issues/49. This was because ref-finance contract on mainnet on updated and so did some deposit requirements get upped. With this PR, to remedy the issue, mainnet archival rpc was added so we can grab the contract from a specific block height instead of the latest block height
=> Adds mainnet archival rpc and fixes ref-finance example

workspaces/Cargo.toml
Cutting a patch version release on top of https://github.com/near/workspaces-rs/pull/46 so that it doesn't stall CI for some projects like `near-sdk-rs`. This won't have any API breaking changes, so should be fine making this a patch version release
=> release: 0.1.1

workspaces/src/network/result.rs
Convenient functions (namely `is_success` and `is_faulure`) for easy assertions discussed in https://github.com/near/near-sdk-rs/pull/699#discussion_r786181686
=> Added `is_success` / `is_failure` for CallExecution results

workspaces/src/rpc/client.rs
This PR aligns `access_key` to behave like all other view queries and make an optimistic (finality-wise) RPC query. This is especially important since `access_key` is also used to make function call transactions, so if you make many calls in a quick succession this can lead to duplicate access key nonces being returned by `access_key`.
=> fix: Make `access_key` do an optimistic RPC query

workspaces/Cargo.toml, workspaces/src/rpc/client.rs, workspaces/tests/create_account.rs, workspaces/tests/deploy.rs
This PR adds logging to RPC client. I made the logs dynamic depending on the logging level enabled. Usually `INFO` would be enough for most users as it prints one-liners with submitted actions and the resulting status. But if a user wants more information (e.g. gas profile, logs etc), they can enable `DEBUG`. Try it out by running tests with `RUST_LOG=workspaces=info`.
=> feat: add rpc logging

examples/src/spooning.rs, workspaces/src/network/mod.rs, workspaces/src/worker/impls.rs, workspaces/tests/patch_state.rs
=> refactor: make patch state key `Vec<u8>` instead of `String`

examples/src/spooning.rs, workspaces/src/network/mod.rs, workspaces/src/worker/impls.rs, workspaces/tests/patch_state.rs
In the end, I had to copy the slices into vectors anyway, not sure if there is a way to avoid that
=> refactor: change patch state parameters to be slices

workspaces/src/network/account.rs, workspaces/src/network/result.rs, workspaces/src/worker/impls.rs
This PR improves error handling on failed transactions and will force the user to handle the error now as an anyhow result. For instance, before this PR, the following would just dangle with the status object returned being ignored at the end.
```
contract.call(function_name)
.args(...)
.transact()
.await?;
```
And after this PR, the `?` error forward at the end will trigger an error on failed transactions. This improves propagating errors such as invalid arguments to calling into a contract function
=> feat: improve error handling on failed transactions

workspaces/src/lib.rs, workspaces/src/network/account.rs, workspaces/src/network/block.rs, workspaces/src/network/mod.rs, workspaces/src/rpc/client.rs, workspaces/src/types.rs, workspaces/src/worker/impls.rs
This adds a couple convenience functions to `Worker` and `Account` types:
- view_account: stuff like balance and storage usage
- view_code
- view_block: to grab latest block timestamps
Also addresses https://github.com/near/workspaces-rs/issues/76
=> chore: Add view_account, view_code, view_block

workspaces/Cargo.toml, workspaces/src/network/server.rs
This suppresses all sandbox logs and allows the user to control it via an environment variable
=> chore: suppress sandbox bin logs

workspaces/src/rpc/client.rs
this ones pretty simple. In the worst case of something going wrong, we shouldn't be waiting 100s to do the last retry and then throw an error at the end. To remedy this, reduce the retries time to a max of 625ms at the worst case
Should close https://github.com/near/workspaces-rs/issues/41 after this one
=> feat: reduce retries time

README.md, workspaces/src/network/account.rs, workspaces/src/network/mod.rs, workspaces/src/rpc/tool.rs
Now no longer polluting working directory with credentials constantly being saved. And now allowing users to store it themselves if they wish to save them.
Also fixed a minor thing with the README title having code formatting.
=> feat: Moved credentials storage to user side

workspaces/src/network/mainnet.rs, workspaces/src/network/mod.rs
Having this fail at runtime is probably not ideal.
=> fix: move TLA creator trait to dev network

examples/src/spooning.rs, workspaces/src/rpc/client.rs, workspaces/src/rpc/patch.rs, workspaces/src/types/account.rs, workspaces/src/worker/impls.rs, workspaces/tests/patch_state.rs
- Removes `StoreKey` from public interface for using prefixes
- Changes state map to have keys as bytes (there is nothing enforcing these to be utf8, this is incorrect)
- Adds helper function to contract struct to retrieve state
=> fix!: Key type of state map and remove exposed primitives type

README.md, workspaces/build.rs, workspaces/src/lib.rs, workspaces/src/network/mainnet.rs, workspaces/src/network/sandbox.rs, workspaces/src/network/testnet.rs, workspaces/src/network/variants.rs, workspaces/src/prelude.rs, workspaces/src/rpc/patch.rs, workspaces/src/types/account.rs, workspaces/src/worker/mod.rs
Been trying for over a day to get `docs.rs` builds to run locally, but keep running into issues with trying to reproduce their builds like unable to find dependencies in the docker container. So felt like it's better just to not waste anymore time trying to configure that and make a release to see if actually passes this time. `DOCS_RS` looks to be the way according to multiple sources so let's go with that. It doesn't affect users who are using the library anyways, but better to get this in sooner than later so people can view the docs.
Also, added some more docs that were missing from the module level
=> hotfix: doc builds on docs.rs

workspaces/src/lib.rs, workspaces/src/network/betanet.rs, workspaces/src/network/mod.rs, workspaces/src/worker/mod.rs
resolves https://github.com/near/workspaces-rs/issues/114.
This adds betanet support to workspaces, while the more general custom network creation is being addressed in a later PR
=> feat: allow Worker<Betanet> creation

CHANGELOG.md, workspaces/build.rs
commit is `1.26.0-rc.2` for now -- tested it works against https://github.com/near/near-sdk-rs/pull/742
=> chore: bump sandbox version default for SDK change

CHANGELOG.md, workspaces/Cargo.toml
Only opinionated thing about this is if the betanet addition should be under an unstable feature flag, but likely the version bump should be minor anyway since sandbox default protocol change shouldn't be a patch version
=> chore: bump workspaces patch version and update changelog

workspaces/src/network/server.rs
Not sure if this is intentional, opening PR more as a question of why this is the case that the process handle can get overwritten here
=> fix: error if sandbox process has already started

workspaces/src/lib.rs, workspaces/src/operations.rs, workspaces/src/rpc/patch.rs, workspaces/src/types/mod.rs, workspaces/tests/types.rs
addresses https://github.com/near/workspaces-rs/issues/130
`SecretKey` now has two new creation methods:
- `from_random`
- `from_str`
~Somewhat breaking API if anyone used `SecretKey::from_seed`, since this PR swapped `near_crypto::KeyType` for `workspaces::types::KeyType`~
edit: nevermind about breaking API, `types` module was never exposed
=> chore: add secret key creation methods and added new KeyType type

README.md, workspaces/src/rpc/client.rs
This will fix timing out on CI with a higher timeout default of 10 seconds instead of 3 and an env var to configure it going forward. The env vars are also now being documented in the README
=> fix: rpc connect timeout

CHANGELOG.md, workspaces/Cargo.toml
Gonna do a patch release to include the fix for rpc timeouts before the error handling https://github.com/near/workspaces-rs/pull/149 gets pulled in since that one has a decent amount of breaking changes and best if users from `0.3.0` could make use of the fixes since.
=> release: 0.3.1

workspaces/src/network/betanet.rs, workspaces/src/network/mainnet.rs, workspaces/src/network/sandbox.rs, workspaces/src/network/testnet.rs, workspaces/src/rpc/client.rs
basing this one off of https://github.com/near/workspaces-rs/pull/105 since we never got to pull it in. This also includes a fix for hyper related: `dispatch dropped without returning error`. The git diff looks horrendous trying to merge into the original PR due to rebasing/squashing, so this one would be faster to just push in
=> fix: avoid creating new client for every request & hyper issues

workspaces/src/rpc/client.rs, workspaces/src/types/account.rs, workspaces/src/types/mod.rs
Addresses https://github.com/near/workspaces-rs/issues/142
Exposes the account keys. Might be a little weird that it's exposed just as a `SecretKey` type instead of something like a `KeyPair` type. This is due to `SecretKey` being a `KeyPair` itself containing the `PublicKey`. WDYT? Is the return type good enough just as `SecretKey` or should we do something like `(PublicKey, SecretKey)`?
=> chore: Expose account keys

.github/workflows/test.yml, examples/src/ref_finance.rs, workspaces/Cargo.toml, workspaces/build.rs, workspaces/src/network/sandbox.rs, workspaces/src/types/account.rs, workspaces/src/types/mod.rs, workspaces/src/worker/impls.rs
This updates nearcore deps to the latest, and also sandbox dep where we now support M1.
Also, since updating to the latest nearcore, there seems to be a bug where the `EnvFilter` in nearcore ignores the case for `stats` target but works for others. So this is causing some stats to be logged every second. Minor annoyance, but will see what's causing it and fix it in the future on a patch release. Getting out M1 support for now in the newest minor patch is more important
=> chore: Update Deps Along w/ M1 Support

.github/workflows/test.yml, CHANGELOG.md, workspaces/Cargo.toml
=> release: 0.4.0

.github/workflows/test.yml, README.md, workspaces/src/types/account.rs
This fixes the current builds failing with the release of 1.63.0 with newer clippy warnings.
- also bumped MSRV to 1.60 since near-primitives 0.14 requires it.
=> fix: tests erroring out on newest rust v1.63.0

README.md
Forgot to update README after 0.4.0 with M1 support
=> fix: Corrected M1 support on README

CHANGELOG.md, workspaces/Cargo.toml
Will release 0.4.1 with the overflow error fix and without error handling included since that's a much bigger breaking change and should be in 0.5.0 instead
=> release: 0.4.1

CHANGELOG.md, README.md, examples/src/croncat.rs, examples/src/fast_forward.rs, examples/src/nft.rs, examples/src/ref_finance.rs, examples/src/spooning.rs, examples/src/status_message.rs, workspaces/src/network/mod.rs, workspaces/src/network/sandbox.rs, workspaces/src/network/testnet.rs, workspaces/src/network/variants.rs, workspaces/src/operations.rs, workspaces/src/prelude.rs, workspaces/src/rpc/patch.rs, workspaces/src/types/account.rs, workspaces/src/worker/impls.rs, workspaces/src/worker/mod.rs, workspaces/tests/batch_tx.rs, workspaces/tests/create_account.rs, workspaces/tests/cross_contract.rs, workspaces/tests/deploy.rs, workspaces/tests/deploy_project.rs, workspaces/tests/optional_args.rs, workspaces/tests/patch_state.rs
Also, no longer require importing `prelude`
=> feat: `worker` no longer required to be passed into arguments when transacting transactions

workspaces/src/types/account.rs
These seemed pretty useful to add since `Account::from_file` didn't make sense if you already had the `SecretKey` value in memory. `Account::set_secret_key` is useful for changing the signer of transactions to use a different one if users had multiple secret keys
=> chore: Added convenience functions `Account::{from_secret_key, set_secret_key}`

README.md, workspaces/src/operations.rs, workspaces/src/types/account.rs
Updating docs:
- better wording for `Transaction`. 
- added the note from https://github.com/near/workspaces-rs/pull/176 to be more precise about recompilation.
- more explicit details about who the signer is when making a call, which should alleviate: https://github.com/near/workspaces-rs/issues/172
- rearranged the README to be more in flow
=> fix: Rewording docs to be more intuitive

workspaces/Cargo.toml, workspaces/src/rpc/client.rs, workspaces/tests/parallel_transactions.rs
This will resolve https://github.com/near/workspaces-rs/issues/163 without requiring the user to specify the nonce manually. The nonce is a value we can cache locally and only need to be retrieved once, incrementing it from thence onwards.
=> fix: Parallel tests should not wait on each other

workspaces/Cargo.toml
Wanted to link to `compile_project` today and noticed it wasn't being added to rust docs.
=> chore: add unstable feature to docs build

workspaces/src/types/account.rs
For whatever reason, you can not do a view call from an `Account`. This simply fixes that functionality.
=> feat: add view calls to an `Account`

workspaces/Cargo.toml, workspaces/src/cargo/mod.rs
This updates the error API in `compile_project` to use latest errors. Also resolves https://github.com/near/workspaces-rs/issues/199 by adding a new error message in the case of missing/incorrect filepath
=> chore: Make compile_project use latest error API

workspaces/Cargo.toml, workspaces/src/network/sandbox.rs, workspaces/src/network/server.rs
This fixes workspaces tests from orphaning the child sandbox process when someone goes to kill the process early, such as the case of a long running test that a user wishes to terminates early because they made changes or whatever reason.
The solution here was to just switch over to the async_process command version which already has this mechanism built-in. They have an external process that kills orphaned processes, and we already needed to switch over to the async version anyways.
=> fix: child sandbox process becoming orphaned on early process termination

examples/Cargo.toml, workspaces/Cargo.toml, workspaces/src/network/testnet.rs, workspaces/src/result.rs, workspaces/src/rpc/client.rs, workspaces/src/rpc/tool.rs, workspaces/src/types/mod.rs, workspaces/tests/types.rs
`near-jsonrpc-client` was officially released, so we do not need to depend on the `-beta.0` version any more.
This upgrade is important because cargo thinks that `0.4.0-beta.0` should be compatible with `0.4.0`, however they are not due to the different versions of the nearcore libraries. This means that `workspaces` fails to compile as a dependency of other crates (unless the `near-jsonrpc-client` version is fixed to the `beta` one in `Cargo.lock`).
Along with the upgrade, there were a few minor API changes in the nearcore libraries which meant we needed to make a few extra changes here (namely around encoding values as base64 / base 58).
=> Chore: Upgrade to version 0.4.0 of near-jsonrpc-client, and version 0.15.0 for nearcore libraries

workspaces/src/operations.rs, workspaces/src/result.rs
This adds a new `Value` type with convenient APIs like `raw_bytes`, `borsh`, and `json` to the value of `ValueOrReceiptId::Value` variant for `ExecutionOutcome`.
Resolves https://github.com/near/workspaces-rs/issues/201
Note that this is a breaking API, so will require a new minor version for this PR
=> chore: Made ValueOrReceiptId::Value object consistent

CHANGELOG.md, examples/src/fast_forward.rs, examples/src/nft.rs, examples/src/ref_finance.rs, examples/src/spooning.rs, examples/src/status_message.rs, workspaces/Cargo.toml, workspaces/src/operations.rs, workspaces/src/rpc/client.rs, workspaces/src/rpc/mod.rs, workspaces/src/rpc/patch.rs, workspaces/src/rpc/query.rs, workspaces/src/types/account.rs, workspaces/src/types/mod.rs, workspaces/src/worker/impls.rs, workspaces/tests/deploy.rs, workspaces/tests/patch_state.rs
This adds the async builder `Query` which allows doing view calls into contract state, account, access keys, code, the view function call, and block. This uses `IntoFuture` to allow calling into `.await` at any point in the builder. Note, that `Query` builder takes a generic `<T>` for the method like `ViewState` since we can define custom builder functions per method type by doing `impl Query<ViewState> { ... }`
cc @matklad if you want to review my use of `IntoFuture` since you initially suggested it
=> feat: Add async builders for `view_*` functions

workspaces/src/operations.rs, workspaces/src/result.rs, workspaces/src/rpc/client.rs, workspaces/src/types/mod.rs
Moves the HashMap key from `AccountId` to `PublicKey`, since we want to associate it based on per-access-key instead of per account
Also, added debug/clone impls for the types that were added in recent PRs
=> fix: Use public keys for cached nonces

examples/simple-contract/Cargo.toml, workspaces/tests/test-contracts/status-message/Cargo.toml, workspaces/tests/test-contracts/status-message/src/lib.rs
metadata was imported but not used previously, was removed in 4.1.
=> fix: remove unused import of metadata

workspaces/Cargo.toml, workspaces/src/error/impls.rs, workspaces/src/error/mod.rs, workspaces/tests/test-contracts/status-message/Cargo.toml
based on https://github.com/near/workspaces-rs/pull/232
Adds in the sandbox error improvement
=> fix: improve err message

workspaces/Cargo.toml, workspaces/tests/query.rs
addresses https://github.com/near/workspaces-rs/issues/226 on workspaces side
=> fix: query variant error on invalid function-name/args

workspaces/src/error/impls.rs, workspaces/src/error/mod.rs
addresses https://github.com/near/workspaces-rs/issues/194.
Thought it would be nice to have these be exposed since the errors are in good shape to be used at higher levels if users want to make use of them to build their own errors. Also added the `Other` variant to `ErrorKind` since users can have different categories of errors other than the ones defined for their higher level workspaces libraries. Any objections to adding this?
=> chore: Expose error creation methods

CHANGELOG.md, examples/Cargo.toml, examples/src/various_queries.rs, workspaces/src/lib.rs, workspaces/src/operations.rs, workspaces/src/rpc/query.rs, workspaces/src/types/block.rs, workspaces/src/types/chunk.rs, workspaces/src/types/mod.rs, workspaces/src/worker/impls.rs
This adds `worker.view_chunk` method for users to call into. Internally, uses `QueryChunk`, since `Query` is more for block reference related queries and nothing else uses `ChunkReference` when making queries.
Also adds a new `various_queries` example to showcase querying both chunk and block data, while being able to query for old contract state data as well.
=> chore: expose `view_chunk`

workspaces/src/network/sandbox.rs, workspaces/src/network/testnet.rs, workspaces/src/operations.rs, workspaces/src/rpc/patch.rs, workspaces/src/types/account.rs, workspaces/src/worker/impls.rs
Since `Worker::view` got changed to be a builder, I noticed that `Worker::call` is no longer consistent with it. So best to make it also return a builder similar to `Account::call` as well. This should come in before [release/0.7.0](https://github.com/near/workspaces-rs/pull/244).
Also, exposed `{Account, Contract}::signer()` since that has been public and can be utilized with `Worker` related methods. Internally cleaned up the storage of `AccountId` in `Account` since `InMemorySigner` already holds the account id.
=> fix: Make call consistent with worker::view

CHANGELOG.md, workspaces/Cargo.toml
Will do a release after this merges
=> release: 0.7.0

CHANGELOG.md, workspaces/src/operations.rs, workspaces/src/rpc/client.rs, workspaces/src/types/account.rs, workspaces/src/worker/impls.rs
Addresses #248
There are probably further improvements I could make to the API of workspace now that Client has a clone instance, but I wanted to start with a PR with a small footprint and get feedback.
=> Removed the lifetime in transact_async

workspaces/Cargo.toml, workspaces/src/error/impls.rs, workspaces/src/network/config.rs, workspaces/src/network/sandbox.rs, workspaces/src/network/server.rs, workspaces/src/rpc/patch.rs
Port collision would rarely happen, but happens pretty frequently on a machine with not as much resources to run a lot of nodes. This fix remedies this problem by adding a couple lockfiles to the ports until the server actually runs and fully acquires the port.
Not sure if this the best way of achieving this, so feel free to suggest anything different.
=> fix: port collision on large amount of tests

workspaces/src/error/impls.rs, workspaces/src/rpc/tool.rs, workspaces/src/types/account.rs, workspaces/tests/create_account.rs
Notice this minor issue where storing the credentials doesn't store the parent id for a subaccount (i.e. `sub.parent` would get stored as `sub.json`). This was due to `Path::set_extension("json")`  setting `parent` into `json` which I didn't notice earlier till now.
=> fix: storing credentials

workspaces/src/error/impls.rs, workspaces/src/rpc/patch.rs
Someone might want to set a different account-id for the imported contract than the original one. For example, let's say a user wants to import a contract multiple times into different accounts to test various states of them in parallel in the same sandbox. That isn't possible right now, so this PR should remedy that.
Sample usage:
```rust
worker.import_contract("contract.id".parse()?)
.dest_account_id("other.id".parse()?)
.transact()
.await?;
```
=> chore: Added destination account-id for `import_contract` call

CHANGELOG.md, workspaces/src/types/mod.rs, workspaces/tests/types.rs
This just adds a couple convenience methods over from `near_crypto` crate. This was originally requested with just `Hash` impl in https://github.com/near/workspaces-rs/issues/263, but decided to import a couple more functions as they are convenient to have if people are managing public keys with workspaces
=> chore: Import some functions over from near_crypto for PublicKey

README.md, examples/manually-spawned-sandbox.md, workspaces/src/error/impls.rs, workspaces/src/network/builder.rs, workspaces/src/network/mod.rs, workspaces/src/network/sandbox.rs, workspaces/src/network/server.rs, workspaces/src/worker/impls.rs, workspaces/src/worker/mod.rs, workspaces/tests/deploy.rs
This adds a `Builder` to the return type of `workspaces::sandbox()` which is another async builder so that users can parameterize what RPC url they want to point to if they have a different RPC node pointing to that network. For this PR, only sandbox was done, and will add `testnet` and `mainnet` after since those are pretty trivial in comparison.
Sandbox now basically has the ability to connect to a user's own locally spawned sandbox node.
=> feat: workspaces::sandbox() can connect to user provided sandbox node 

.github/workflows/test.yml, README.md, examples/Cargo.toml, examples/src/ref_finance.rs, workspaces/Cargo.toml, workspaces/src/types/mod.rs
The PR updates the `borsh` dependency up to 0.10 and other.
=> chore: bump borsh version and other deps

workspaces/src/network/betanet.rs, workspaces/src/network/mainnet.rs, workspaces/src/network/mod.rs, workspaces/src/network/testnet.rs, workspaces/src/worker/mod.rs
Second part of https://github.com/near/workspaces-rs/pull/220
This implements the `NetworkBuilder` for testnet and mainnet networks so that these networks can customize the RPC urls to point to Pagoda ones or their own RPC. Also made, `RPC_URL` and `ARCHIVAL_URL` constants public, since users can make use of them if they want to.
=> feat: add `NetworkBuilder` impl for mainnet, betanet and testnet

.github/workflows/test.yml, .gitignore, workspaces/Cargo.toml, workspaces/src/cargo/mod.rs
replaced existing build logic to use cargo near to resolve #230
=> Enhancement : Use cargo near to build project

CHANGELOG.md, workspaces/Cargo.toml, workspaces/src/lib.rs, workspaces/src/network/mod.rs, workspaces/src/network/server.rs, workspaces/tests/deploy.rs
This PR fixes the problem where users were getting firewall popups when running integration tests on MacOS as described in #276.
It turns out this had two causes:
1. `neard` was running on `0.0.0.0` instead of `localhost`.
2. The [`portpicker`](https://github.com/Dentosal/portpicker-rs) library used to acquire free random ports was testing ports by binding to `0.0.0.0`.
This PR fixes both causes. 
The PR changes how `neard` is ran by using the more verbose `run_with_options` where we can specify CLI arguments to `neard`. We use this to specify the IP address as localhost. Previously only the port numbers were specified and `neard` defaulted to running on `0.0.0.0`.
This PR also removes the `portpicker` library and provides a simple function to pick random port numbers with the OS feature …
=> Run `neard` on `localhost` instead of `0.0.0.0` to prevent firewall popups on MacOS

README.md, workspaces/src/network/betanet.rs, workspaces/src/network/builder.rs, workspaces/src/network/sandbox.rs, workspaces/src/network/server.rs, workspaces/src/operations.rs, workspaces/src/rpc/query.rs, workspaces/src/types/account.rs, workspaces/src/types/mod.rs
As I was going through the code source, I have some small typos here and there, this is small PR aims to fix that.
=> fix: fix typos

.github/workflows/test.yml, README.md, workspaces/build.rs
The issue involving wasm contract builds for Rust toolchain 1.70 and later: https://github.com/near/nearcore/issues/9143 has been resolved 
Should be ok to update the toolchain.
<s>Are we updating to toolchain `1.70` or ok to use `stable`?</s>
=> chore: upgrade to stable toolchain

README.md, workspaces/src/worker/impls.rs
Closes https://github.com/near/workspaces-rs/issues/229
=> chore: improve fast_forward docs

workspaces/src/types/gas_meter.rs
=> chore: Restrict GasHook type to require RefUnwindSafe and UnwindSafe to avoid breaking release

README.md, examples/src/croncat.rs, examples/src/nft.rs, examples/src/ref_finance.rs, workspaces/Cargo.toml, workspaces/src/network/sandbox.rs, workspaces/src/network/testnet.rs, workspaces/src/operations.rs, workspaces/src/result.rs, workspaces/src/rpc/client.rs, workspaces/src/rpc/patch.rs, workspaces/src/rpc/query.rs, workspaces/src/types/account.rs, workspaces/src/types/block.rs, workspaces/src/types/chunk.rs, workspaces/src/types/mod.rs, workspaces/src/types/token.rs, workspaces/src/worker/impls.rs, workspaces/tests/account.rs, workspaces/tests/batch_tx.rs, workspaces/tests/cross_contract.rs, workspaces/tests/gas_meter.rs, workspaces/tests/optional_args.rs, workspaces/tests/patch_state.rs, workspaces/tests/query.rs
Closes https://github.com/near/near-workspaces-rs/issues/332
=> refactor: Migrate to NearToken

workspaces/src/lib.rs, workspaces/src/rpc/client.rs
This was flagged by clippy with `nursery` lints enabled:
```
cargo clippy --all-features --workspace -- --warn clippy::all --warn clippy::nursery
```
(There are more warnings to address in #328)
=> fix: Fixed await during acquired lock in rpc::client::fetch_tx_nonce

.github/workflows/test.yml, examples/src/croncat.rs, examples/src/spooning.rs, workspaces/src/error/impls.rs, workspaces/src/network/builder.rs, workspaces/src/result.rs, workspaces/src/rpc/client.rs, workspaces/src/rpc/patch.rs, workspaces/src/types/account.rs, workspaces/src/types/chunk.rs, workspaces/src/types/gas_meter.rs, workspaces/src/types/mod.rs, workspaces/src/worker/impls.rs, workspaces/src/worker/mod.rs
The motivation to propose these changes is to add the possibility of using this crate in projects which are checked with clippy with lints `all` and `nursery`.
=> chore: apply suggestions proposed by clippy

CHANGELOG.md, workspaces/Cargo.toml
* `near-workspaces`: 0.8.0 -> 0.9.0 (✓ API compatible changes)
<blockquote>
- Require Send + Sync for T in Worker<T> to allow near-workspaces usage in multithreading async runtimes  ([#328](https://github.com/near/near-workspaces-rs/pull/328))
- Added API for measuring gas ([#284](https://github.com/near/near-workspaces-rs/pull/284))
- Fixed await during acquired lock in rpc::client::fetch_tx_nonce ([#334](https://github.com/near/near-workspaces-rs/pull/334))
- [**breaking**] Migrate to use NearToken instead of raw u128 for balance variables to ensure strict typing ([#333](https://github.com/near/near-workspaces-rs/pull/333))
- Restrict GasHook type to require RefUnwindSafe and UnwindSafe to avoid breaking release …
=> chore: release v0.9.0

workspaces/src/operations.rs, workspaces/src/rpc/client.rs, workspaces/src/types/gas_meter.rs, workspaces/src/types/mod.rs, workspaces/src/worker/impls.rs, workspaces/src/worker/mod.rs
~Also resolving https://github.com/near/near-workspaces-rs/issues/153~
=> chore: cleanup internals

examples/Cargo.toml, examples/src/croncat.rs, examples/src/spooning.rs, workspaces/Cargo.toml, workspaces/src/cargo/mod.rs, workspaces/src/types/account.rs
Dependencies upgraded:
- serde_with
- ~cargo-near~
- borsh (examples)
=> chore: dependecy bumps

workspaces/src/result.rs
In my tests I need to clone: `pub type ExecutionSuccess = ExecutionResult<Value>;`
`ExecutionResult` itself is clonable but `Value` is not so I think it should be clonable too.
I guess the tests should pass after this PR: https://github.com/near/near-workspaces-rs/pull/343?
=> fix: add clone to result value

CHANGELOG.md, workspaces/Cargo.toml
* `near-workspaces`: 0.9.0 -> 0.10.0 (✓ API compatible changes)
<blockquote>
- Impl Clone on result Value ([#345](https://github.com/near/near-workspaces-rs/pull/345))
- Upgraded NEAR crates to 0.20.0 release ([#346](https://github.com/near/near-workspaces-rs/pull/346))
- dependecy bumps ([#338](https://github.com/near/near-workspaces-rs/pull/338))
- cleanup internals ([#329](https://github.com/near/near-workspaces-rs/pull/329))
- use stable sandbox by default ([#335](https://github.com/near/near-workspaces-rs/pull/335))
- [**breaking**] Remove `interop_sdk` feature from defaults ([#339](https://github.com/near/near-workspaces-rs/pull/339))
- fix typos ([#340](https://github.com/near/near-workspaces-rs/pull/340))
</blockquote> …
=> chore: release v0.10.0

workspaces/src/network/variants.rs
This issue: https://github.com/near/near-workspaces-rs/issues/156 and my PR: https://github.com/near/near-workspaces-rs/pull/350 indicate that it is not clear for users how to create a dev account with more than 100 Near.
Closes: https://github.com/near/near-workspaces-rs/issues/156
=> docs: a way to get account with more than 100 near on sandbox

CHANGELOG.md, workspaces/Cargo.toml
* `near-workspaces`: 0.10.0 -> 0.10.1
<blockquote>
- Exposes status RPC API method ([#308](https://github.com/near/near-workspaces-rs/pull/308))
- Fixed `dev_deploy` to use registrar account to create top-level accounts (nearcore 1.37.0+ forbidden to create top-level accounts by non-registrar accounts) ([#360](https://github.com/near/near-workspaces-rs/pull/360))
- Re-exported near-abi-client ([#303](https://github.com/near/near-workspaces-rs/pull/303))
- a way to get account with more than 100 near on sandbox ([#351](https://github.com/near/near-workspaces-rs/pull/351))
- Updated cargo-near to "0.5.2" ([#347](https://github.com/near/near-workspaces-rs/pull/347))
</blockquote>
</p></details>
---
This PR was generated with …
=> chore: release v0.10.1

CHANGELOG.md, workspaces/Cargo.toml
* `near-workspaces`: 0.10.1 -> 0.11.0
<blockquote>
- Upgraded deps ([#363](https://github.com/near/near-workspaces-rs/pull/363))
</blockquote>
</p></details>
---
=> chore: release v0.11.0

workspaces/src/rpc/tool.rs
Close https://github.com/near/near-workspaces-rs/issues/353
=> Handling account creation request errors

CHANGELOG.md, workspaces/Cargo.toml
* `near-workspaces`: 0.11.0 -> 0.11.1
<blockquote>
- Gracefully handle account creation request errors from a faucet service [testnet-only] ([#366](https://github.com/near/near-workspaces-rs/pull/366))
</blockquote>
</p></details>
---
=> chore: release v0.11.1

CHANGELOG.md, workspaces/Cargo.toml
* `near-workspaces`: 0.11.1 -> 0.12.0
<blockquote>
- [**breaking**] upgraded near deps to 0.24 ([#370](https://github.com/near/near-workspaces-rs/pull/370))
</blockquote>
</p></details>
---
=> chore: release v0.12.0

examples/Cargo.toml, examples/noop-contract/Cargo.toml, examples/simple-contract/Cargo.toml, workspaces/Cargo.toml, workspaces/tests/test-contracts/status-message/Cargo.toml, workspaces/tests/test-contracts/type-serialize/Cargo.toml
Sandbox has not been updated as it's broken on Mac OS.
See https://github.com/near/nearcore/issues/12062
=> chore!: updates near-* dependencies to 0.25

CHANGELOG.md, workspaces/Cargo.toml
* `near-workspaces`: 0.13.0 -> 0.14.0
<blockquote>
- [**breaking**] Updated near-* dependencies to 0.26 release ([#377](https://github.com/near/near-workspaces-rs/pull/377))
</blockquote>
</p></details>
---
=> chore: release v0.14.0

workspaces/src/operations.rs
The `TransactionStatus::status` call should not be waiting for `Final` inclusion of the transaction as it is supposed to only be checking the status of the transaction on chain and not wait for it to completely complete. Also, this does not take away any feature as `TransactionStatus::wait` already does the full wait
=> fix: TransactionStatus::status should not be waiting for Final

CHANGELOG.md, workspaces/Cargo.toml
* `near-workspaces`: 0.14.0 -> 0.14.1 (✓ API compatible changes)
<blockquote>
- TransactionStatus::status should not be waiting for Final ([#379](https://github.com/near/near-workspaces-rs/pull/379))
- fix clippy 1.82 (doc preambles) ([#381](https://github.com/near/near-workspaces-rs/pull/381))
- bump cargo-near-build to 0.2.0 ([#380](https://github.com/near/near-workspaces-rs/pull/380))
</blockquote>
</p></details>
---
=> chore: release v0.14.1

workspaces/Cargo.toml
this is merely sync with its not being used outside of `cargo` module : https://github.com/near/near-workspaces-rs/blob/main/workspaces/src/lib.rs#L10
=> chore: make cargo-near-build optional in manifest

workspaces/Cargo.toml, workspaces/src/lib.rs
PR addresses this TODO https://github.com/near/near-sdk-rs/pull/1253#discussion_r1833629296 , which later ~will be~ has been removed from `near-sdk` code, for cases:
1. when non-async function is required in `static std::sync::OnceLock<T>/LazyLock<T, F>` creation like here https://github.com/dj8yfo/near-sdk-rs/blob/7be211e1b2991f6c5b4db78972784dac2f066e32/examples/fungible-token/tests/workspaces.rs#L47
2. when non-default build is required like with `no-abi` here https://github.com/dj8yfo/abstract-dao/blob/fe9d16797bf582f0ea24380c1e4ad6bdb8c97283/tests/common.rs#L33
PR avoids necessity to import `cargo-near-build` separately as a dependency
PR should best be published with a major release, to avoid weird breakage `0.14.1 -> 0.14.x`
=> chore!: reexport `cargo-near-build` for configurable build if needed

.github/workflows/test.yml
this says it clears additional 27 GB
=> ci: add `jlumbroso/free-disk-space` to `./github/workflows/test.yml`

CHANGELOG.md, workspaces/Cargo.toml
* `near-workspaces`: 0.14.1 -> 0.15.0 (✓ API compatible changes)
<blockquote>
- [**breaking**] updates near-* dependencies to 0.27 release ([#387](https://github.com/near/near-workspaces-rs/pull/387))
- [**breaking**] reexport `cargo-near-build` for configurable build if needed ([#386](https://github.com/near/near-workspaces-rs/pull/386))
- make cargo-near-build optional in manifest ([#383](https://github.com/near/near-workspaces-rs/pull/383))
</blockquote>
</p></details>
---
=> chore: release v0.15.0

CODEOWNERS, examples/Cargo.toml, examples/noop-contract/Cargo.toml, examples/simple-contract/Cargo.toml, workspaces/Cargo.toml, workspaces/src/rpc/query.rs, workspaces/src/types/chunk.rs, workspaces/tests/test-contracts/status-message/Cargo.toml, workspaces/tests/test-contracts/type-serialize/Cargo.toml
=> chore!: updates near-* dependencies to 0.28 release

workspaces/src/network/sandbox.rs, workspaces/src/network/server.rs, workspaces/src/worker/mod.rs
looks like this was a new lint from https://github.com/rust-lang/rust/issues/48919 , 
and the lint was correct about `fs2::FileExt` vs
```rust
#[unstable(feature = "file_lock", issue = "130994")]
pub fn unlock(&self) -> io::Result<()> {
self.inner.unlock()
}
```
=> ci: fix new compile warn and clippy of 1.84

.github/workflows/test.yml, workspaces/tests/query.rs
resolves #404 
As https://github.com/rust-lang/rust-clippy/issues/14363#issuecomment-2704478896 pointed out it makes little sense to test fresh/new/somewhat-unstable lints with `near-workspaces-rs`'s ci
=> ci: remove clippy::nursery

CHANGELOG.md, workspaces/Cargo.toml
* `near-workspaces`: 0.17.0 -> 0.18.0 (✓ API compatible changes)
<blockquote>
- [**breaking**] updates near-* dependencies to 0.29 release ([#407](https://github.com/near/near-workspaces-rs/pull/407))
- remove repetitive words ([#408](https://github.com/near/near-workspaces-rs/pull/408))
- remove clippy::nursery ([#406](https://github.com/near/near-workspaces-rs/pull/406))
- cache @v1 -> @v2; + clippy 1.85 ([#403](https://github.com/near/near-workspaces-rs/pull/403))
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/release-plz/release-plz/).
=> chore: release v0.18.0

.github/workflows/test.yml, workspaces/Cargo.toml, workspaces/src/cargo/mod.rs
this depends on https://github.com/near/cargo-near/pull/333
additionally this has been tested in scope of https://github.com/near/near-sdk-rs/pull/1350
=> feat: replace cargo-near-build with patch from feat/build-external-method branch

CHANGELOG.md, workspaces/Cargo.toml
* `near-workspaces`: 0.18.0 -> 0.19.0 (✓ API compatible changes)
<blockquote>
- [**breaking**] build with external `cargo-near` binary CLI in `near_workspaces::compile_project` ([#411](https://github.com/near/near-workspaces-rs/pull/411))
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/release-plz/release-plz/).
=> chore: release v0.19.0

CHANGELOG.md, workspaces/Cargo.toml
* `near-workspaces`: 0.19.0 -> 0.20.0 (⚠ API breaking changes)
```text
--- failure struct_pub_field_missing: pub struct's pub field removed or renamed ---
Description:
A publicly-visible struct has at least one public field that is no longer available under its prior name. It may have been renamed or removed entirely.
ref: https://doc.rust-lang.org/cargo/reference/semver.html#item-remove
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.41.0/src/lints/struct_pub_field_missing.ron
Failed in:
field code_hash of struct AccountDetailsPatch, previously in file /tmp/.tmpscwjix/near-workspaces/src/types/account.rs:337
field code_hash of struct AccountDetailsPatch, previously in file /tmp/.tmpscwjix/near-workspaces/src/types/account.rs:337
field code_hash of struct AccountDetails, …
```
=> chore: release v0.20.0

workspaces/src/network/variants.rs
we've discussed and @akorchyn considered that using the same key for all dev-accounts in sandbox is super dumb
=> use long random account id or account id prefix as secret key seed

CHANGELOG.md, workspaces/Cargo.toml
* `near-workspaces`: 0.20.0 -> 0.20.1 (✓ API compatible changes)
<blockquote>
- use long random account id or account id prefix as secret key seed ([#416](https://github.com/near/near-workspaces-rs/pull/416))
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/release-plz/release-plz/).
=> chore: release v0.20.1

CHANGELOG.md, workspaces/Cargo.toml
* `near-workspaces`: 0.20.1 -> 0.21.0
</p></details>
---
This PR was generated with [release-plz](https://github.com/release-plz/release-plz/).
=> chore: release v0.21.0
